"""
streamlit_app/pdf_exporter.py

PDF Exporter Module for CareerCast Streamlit Dashboard.
Generates styled PDF summary reports for candidate career path predictions,
skill gap analysis, and course learning roadmaps.
"""

import os
from typing import Dict, Any, List

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False


class CareerReportPDF(FPDF if HAS_FPDF else object):
    def header(self):
        if not HAS_FPDF:
            return
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(99, 102, 241)  # #6366f1 Indigo
        self.cell(0, 10, "CAREERCAST AI CAREER INTELLIGENCE REPORT", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(148, 163, 184)
        self.cell(0, 5, "Infosys Springboard Internship - AI Career Recommendation System", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)
        self.set_draw_color(99, 102, 241)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        if not HAS_FPDF:
            return
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by CareerCast AI Engine", align="C")


def generate_pdf_bytes(report_data: Dict[str, Any]) -> bytes:
    """Generates PDF bytes for candidate career report."""
    if not HAS_FPDF:
        # Fallback to plain text bytes if fpdf2 is not yet installed
        text_report = f"""CAREERCAST CAREER INTELLIGENCE REPORT
Target Career: {report_data.get('target_career', 'N/A')}
Match Score: {report_data.get('match_score', 0):.1f}%

Matched Skills: {', '.join(report_data.get('matched_skills', []))}
Missing Skills: {', '.join(report_data.get('missing_skills', []))}

Top Recommended Courses:
"""
        for c in report_data.get('recommended_courses', []):
            text_report += f"- {c.get('course_name')} ({c.get('provider')})\n"
        return text_report.encode("utf-8")

    pdf = CareerReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Candidate Overview Section
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, "1. Executive Profile Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    
    target_career = report_data.get("target_career", "ML Engineer")
    match_score = report_data.get("match_score", 0.0)
    
    pdf.cell(0, 6, f"Target Career Path: {target_career}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Overall Skill Alignment: {match_score:.1f}%", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Top Predictions
    if "top_predictions" in report_data:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, "2. Ensemble Model Predictions", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for pred in report_data["top_predictions"][:5]:
            pdf.cell(0, 6, f" - {pred['career']}: {pred['confidence']:.1f}% Confidence", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # Skill Gap Section
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, "3. Skill Gap Analysis", new_x="LMARGIN", new_y="NEXT")
    
    matched = report_data.get("matched_skills", [])
    missing = report_data.get("missing_skills", [])

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(4, 120, 87) # Green
    pdf.cell(0, 6, f"Matched Skills ({len(matched)}): {', '.join(matched) if matched else 'None'}", new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(185, 28, 28) # Red
    pdf.cell(0, 6, f"Missing Skills ({len(missing)}): {', '.join(missing) if missing else 'None'}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Recommended Courses Section
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, "4. Recommended Learning Roadmap", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)

    courses = report_data.get("recommended_courses", [])
    if courses:
        for idx, course in enumerate(courses, 1):
            course_line = f"{idx}. {course.get('course_name')} ({course.get('provider')}) - Skill: {course.get('skill_covered')} [{course.get('difficulty')}]"
            pdf.cell(0, 6, course_line, new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(0, 6, "No additional course gap recommendations required.", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())
